apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: landing-page
  name: landing-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
      - image: asefamarudin/landing-page-sample:19
        name: landing-page
