apiVersion: v1
kind: Service
metadata:
  labels:
    app: landing-page
  name: landing-page
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: landing-page
  type: LoadBalancer
