name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: self-hosted

    steps:
        
    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: asefamarudin/app:latest
      
